services:
  l4d2:
    image: left4devops/l4d2:latest
    container_name: l4d2
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
    volumes:
      - ./data:/home/steam/l4d2-dedicated
    restart: unless-stopped

